{
    "name": "eslint-plugin-error-cause",
    "version": "1.2.3",
    "description": "ESLint rules to detect swallowed error causes when rethrowing exceptions.",
    "main": "dist/index.js",
    "scripts": {
        "test": "vitest --run",
        "build": "tsc --build tsconfig.build.json",
        "lint": "pnpm run \"/^lint:.*/\"",
        "lint:docs": "markdownlint --config .markdownlintrc.json \"**/*.md\"",
        "lint:eslint-docs": "eslint-doc-generator --check",
        "lint:js": "eslint .",
        "update:eslint-docs": "eslint-doc-generator"
    },
    "files": [
        "dist"
    ],
    "repository": {
        "type": "git",
        "url": "https://github.com/Amnish04/eslint-plugin-error-cause"
    },
    "homepage": "https://dev.to/amnish04/never-lose-valuable-error-context-in-javascript-3aco",
    "keywords": [
        "eslint",
        "eslintplugin",
        "eslint-plugin",
        "typescript",
        "lint",
        "error",
        "cause",
        "errors",
        "plugin"
    ],
    "author": "Amnish Singh Arora",
    "license": "ISC",
    "devDependencies": {
        "@eslint/js": "^9.26.0",
        "@types/node": "^22.15.3",
        "@typescript-eslint/parser": "^8.32.1",
        "@typescript-eslint/rule-tester": "^8.32.1",
        "eslint": "^9.26.0",
        "eslint-doc-generator": "^2.1.2",
        "eslint-plugin-eslint-plugin": "^6.4.0",
        "eslint-plugin-n": "^17.17.0",
        "globals": "^16.1.0",
        "markdownlint-cli": "^0.45.0",
        "typescript": "^5.8.3",
        "typescript-eslint": "^8.32.0",
        "vitest": "^3.1.3"
    },
    "dependencies": {
        "@typescript-eslint/utils": "^8.32.1"
    },
    "peerDependencies": {
        "@typescript-eslint/parser": ">=8.32.1",
        "eslint": ">=9.0.0",
        "typescript": ">=5.0.0"
    },
    "engines": {
        "node": ">=16.9.0"
    }
}
